### ISSUE TITLE
[Feature] implement backend part of the app

### ISSUE THREAD

**Issue by eLeontev** [eLeontev/mind-map#16]
As user I'm able to use next REST API:
POST:/maps/new - create new map
SAVE:/maps/{id} - save the map by id
REMOVE:/maps/{id} - remove the map by id

**Comment by kdhttps** [comment]
I will do this as given below step
1. REST API using node with mongodb
2. I'll push this into `app` new folder in your github root.

if you are ok then I'll push changes

**Comment by eLeontev** [comment]
One more, please implement it in `src/server` folder. no connection to `frontend` part also. Just clear REST on node:) 

next map structure preferable: {id:String, label:String, owner:String, isShared:Boolean}

**Comment by kdhttps** [comment]
Ok, I'll take care of this things

**Comment by kdhttps** [comment]
Made PR, review it https://github.com/eLeontev/mind-map/pull/17

**Comment by eLeontev** [comment]
completed
