### ISSUE TITLE
Update - include pretter

### ISSUE THREAD

**Issue by eLeontev** [eLeontev/mind-map#3]
include  **pretter**  and setup it to common airnbnb es6 to follow common style-guide

**Comment by dhkamp** [comment]
Do you want to only have prettier included or also eslint?

**Comment by JoelLau** [comment]
@eLeontev hi, if anyone hasn't already, I would like to work on this 😁 

can I just check if you are generating your package.json files via npm or yarn?

**Comment by eLeontev** [comment]
done. thanks
